type Todo {
  id: String!
  title: String!
  checked: Boolean!
}

input TodoInput {
  id: String!
  title: String!
  checked: Boolean!
}

type Query {
  allTodos: [Todo]
}

type Mutation {
  createTodo(todo: TodoInput!): Todo
  deleteTodo(id: String!): Todo
}